// SIGN UP
export const SIGN_UP_EMAIL = 'SIGN_UP_EMAIL';
export const SIGN_UP_MOBILE = 'SIGN_UP_MOBILE';
export const SIGN_UP_NAME = 'SIGN_UP_NAME';
export const SIGN_UP_PASSWORD = 'SIGN_UP_PASSWORD';
export const SIGN_UP_USERID = 'SIGN_UP_USERID';
export const SIGN_UP_COMPANYNAME = 'SIGN_UP_COMPANYNAME';
export const SIGN_UP_SUBMIT = 'SIGN_UP_SUBMIT';
export const IS_SIGN_UP = 'IS_SIGN_UP';
// LOG IN
export const LOG_IN_USERID = 'LOG_IN_USERID';
export const LOG_IN_PASSWORD = 'LOG_IN_PASSWORD';
export const LOG_IN_CONFIRM = 'LOG_IN_CONFIRM';
export const IS_LOG_IN = 'IS_LOG_IN';
// DASHBOARD
export const DASHBOARD_ALLMEMBER_SHOW = 'DASHBOARD_ALLMEMBER_SHOW';
export const DASHBOARD_CURRENTMEMBER_SHOW = 'DASHBOARD_CURRENTMEMBER_SHOW';
export const DASHBOARD_LATESTACTIVITY_SHOW = 'DASHBOARD_LATESTACTIVITY_SHOW';
export const DASHBOARD_ROOMRESERVE_SHOW = 'DASHBOARD_ROOMRESERVE_SHOW';
export const IS_DASHBOARD_SHOW = 'IS_DASHBOARD_SHOW';
// LEAD
export const LEAD_DATA = 'LEAD_DATA';
export const LEAD_AXIOS_DATA_GET = 'LEAD_AXIOS_DATA_GET';
